import Foundation
import MapKit

class LocationData {
    static let locations: [Location] = [
        Location(name: "성이시돌목장",
                 locationType: "관광지",
                 address: "제주시 한림읍 산록남로 53",
                 coordinates: CLLocationCoordinate2D(latitude: 33.487198, longitude: 126.531686),
                 openHours: "09:00~21:00",
                 dogSize: "소형견, 중형견, 대형견",
                 hashTags: "#구름#제주",
                 description: "목줄 2m 이내, 배변 봉투 지참, 성이시돌목장 카페 내부는 출입 불가",
                 imageName: "https://api.cdn.visitjeju.net/photomng/imgpath/201812/21/0e98f747-2431-4e0d-a3d0-e2d0886b3dfc.JPG"),
        Location(name: "스누피가든",
                 locationType: "관광지",
                 address: "제주시 구좌읍 금백조로 930",
                 coordinates: CLLocationCoordinate2D(latitude: 33.452342, longitude: 126.569523),
                 openHours: "09:00~18:00",
                 dogSize: "소형견, 중형견, 대형견",
                 hashTags: "#구름#제주",
                 description: "목줄 2m 이내, 배변 봉투 지참, 매주 수요일 '반려동물 데이'에만 입장 가능, 안전한 관람을 위해 1인 1마리까지만 입장가능, 실내에서는 케이지 내 보호 또는 유모차 내에 탑승(케이지 없을 시 야외 가든만 이용 가능), 반려동물 동반시 도슨트 프로그램 잠여 및 가든 셔틀버스 이용이 어려움, 입질/공격성이 있거나 잔 짖음이 심해 주변피해가 있을 경우 퇴장조치 있을 수 있음",
                 imageName: "https://api.cdn.visitjeju.net/photomng/imgpath/202012/16/2ec86865-a3c7-4ba3-8d0e-3ebf3900bc97.jpg"),
        Location(name: "도치돌알파카목장",
                 locationType: "관광지",
                 address: "제주특별자치도 서귀포시 성산읍 동류암로 20",
                 coordinates: CLLocationCoordinate2D(latitude: 33.449830, longitude: 126.918169),
                 openHours: "10:00~18:00",
                 dogSize: "소형견, 중형견",
                 hashTags: "#구름#제주",
                 description: "10kg 미만, 목줄 2m 이내, 이동 시 케이지 사용 및 꼭 안고 이동해야함.",
                 imageName: "https://api.cdn.visitjeju.net/photomng/imgpath/202012/14/5a1307d3-dff0-455a-8474-2448949f8ab1.jpg"),
        
        Location(name: "구룸스퀘어 인 제주",
                 locationType: "관광지",
                 address: "제주특별자치도 제주시 도남로 168-12",
                 coordinates: CLLocationCoordinate2D(latitude: 33.487198, longitude: 126.531686),
                 openHours: "09:00~21:00",
                 dogSize: "대형견",
                 hashTags: "#구름#제주",
                 description: "구름톤 첫째날 장소",
                 imageName: nil),
        Location(name: "카카오 스페이스닷원",
                 locationType: "관광지",
                 address: "제주특별자치도 제주시 첨단로 242",
                 coordinates: CLLocationCoordinate2D(latitude: 33.452342, longitude: 126.569523),
                 openHours: "09:00~21:00",
                 dogSize: "대형견",
                 hashTags: "#구름#제주",
                 description: "구름톤 둘째날 장소",
                 imageName: nil),
        Location(name: "플레이스캠프 제주",
                 locationType: "관광지",
                 address: "제주특별자치도 서귀포시 성산읍 동류암로 20",
                 coordinates: CLLocationCoordinate2D(latitude: 33.449830, longitude: 126.918169),
                 openHours: "09:00~21:00",
                 dogSize: "대형견",
                 hashTags: "#구름#제주",
                 description: "구름톤 해커톤 장소",
                 imageName: nil),
        
    ]
    
    static let location_dummys: [Location] = [
        Location(name: "성이시돌목장",
                 locationType: "관광지",
                 address: "제주시 한림읍 산록남로 53",
                 coordinates: CLLocationCoordinate2D(latitude: 33.487198, longitude: 126.531686),
                 openHours: "09:00~21:00",
                 dogSize: "소형견, 중형견, 대형견",
                 hashTags: "#구름#제주",
                 description: "목줄 2m 이내, 배변 봉투 지참, 성이시돌목장 카페 내부는 출입 불가",
                 imageName: "https://api.cdn.visitjeju.net/photomng/imgpath/201812/21/0e98f747-2431-4e0d-a3d0-e2d0886b3dfc.JPG"),
        Location(name: "스누피가든",
                 locationType: "관광지",
                 address: "제주시 구좌읍 금백조로 930",
                 coordinates: CLLocationCoordinate2D(latitude: 33.452342, longitude: 126.569523),
                 openHours: "09:00~18:00",
                 dogSize: "소형견, 중형견, 대형견",
                 hashTags: "#구름#제주",
                 description: "목줄 2m 이내, 배변 봉투 지참, 매주 수요일 '반려동물 데이'에만 입장 가능, 안전한 관람을 위해 1인 1마리까지만 입장가능, 실내에서는 케이지 내 보호 또는 유모차 내에 탑승(케이지 없을 시 야외 가든만 이용 가능), 반려동물 동반시 도슨트 프로그램 잠여 및 가든 셔틀버스 이용이 어려움, 입질/공격성이 있거나 잔 짖음이 심해 주변피해가 있을 경우 퇴장조치 있을 수 있음",
                 imageName: "https://api.cdn.visitjeju.net/photomng/imgpath/202012/16/2ec86865-a3c7-4ba3-8d0e-3ebf3900bc97.jpg"),
        Location(name: "도치돌알파카목장",
                 locationType: "관광지",
                 address: "제주특별자치도 서귀포시 성산읍 동류암로 20",
                 coordinates: CLLocationCoordinate2D(latitude: 33.449830, longitude: 126.918169),
                 openHours: "10:00~18:00",
                 dogSize: "소형견, 중형견",
                 hashTags: "#구름#제주",
                 description: "10kg 미만, 목줄 2m 이내, 이동 시 케이지 사용 및 꼭 안고 이동해야함.",
                 imageName: "https://api.cdn.visitjeju.net/photomng/imgpath/202012/14/5a1307d3-dff0-455a-8474-2448949f8ab1.jpg"),
        
    ]
}


