import Foundation
import MapKit

class LocationData {
    static let locations: [Location] = [
        Location(name: "성이시돌목장",
                 locationType: "관광지",
                 address: "제주시 한림읍 산록남로 53",
                 coordinates: CLLocationCoordinate2D(latitude: 33.487198, longitude: 126.531686),
                 openHours: "09:00~21:00",
                 dogSize: "소형견, 중형견, 대형견",
                 hashTags: "#탁트인 #활달한",
                 description: "목줄 2m 이내, 배변 봉투 지참, 성이시돌목장 카페 내부는 출입 불가",
                 imageName: "https://api.cdn.visitjeju.net/photomng/imgpath/201812/21/0e98f747-2431-4e0d-a3d0-e2d0886b3dfc.JPG"),
        Location(name: "스누피가든",
                 locationType: "관광지",
                 address: "제주시 구좌읍 금백조로 930",
                 coordinates: CLLocationCoordinate2D(latitude: 33.461903, longitude: 126.484016),
                 openHours: "09:00~18:00",
                 dogSize: "소형견, 중형견, 대형견",
                 hashTags: "#대형견 #스누피",
                 description: "목줄 2m 이내, 배변 봉투 지참, 매주 수요일 '반려동물 데이'에만 입장 가능, 안전한 관람을 위해 1인 1마리까지만 입장가능, 실내에서는 케이지 내 보호 또는 유모차 내에 탑승(케이지 없을 시 야외 가든만 이용 가능), 반려동물 동반시 도슨트 프로그램 잠여 및 가든 셔틀버스 이용이 어려움, 입질/공격성이 있거나 잔 짖음이 심해 주변피해가 있을 경우 퇴장조치 있을 수 있음",
                 imageName: "https://api.cdn.visitjeju.net/photomng/imgpath/202012/16/2ec86865-a3c7-4ba3-8d0e-3ebf3900bc97.jpg"),
        Location(name: "도치돌알파카목장",
                 locationType: "관광지",
                 address: "제주특별자치도 서귀포시 성산읍 동류암로 20",
                 coordinates: CLLocationCoordinate2D(latitude: 33.460154, longitude: 126.448384),
                 openHours: "10:00~18:00",
                 dogSize: "소형견, 중형견",
                 hashTags: "#알파카 #중형견",
                 description: "10kg 미만, 목줄 2m 이내, 이동 시 케이지 사용 및 꼭 안고 이동해야함.",
                 imageName: "https://api.cdn.visitjeju.net/photomng/imgpath/202012/14/5a1307d3-dff0-455a-8474-2448949f8ab1.jpg"),
        Location(name: "무병장수테마파크",
                 locationType: "관광지",
                 address: "제주시 애월읍 어음 13길 196",
                 coordinates: CLLocationCoordinate2D(latitude: 33.421734, longitude: 126.405218),
                 openHours: "09:00~21:00",
                 dogSize: "소형견, 중형견, 대형견",
                 hashTags: "#대형견 #애월",
                 description: "목줄 2m 이내, 배변 봉투 지참, 관광지 내 카페 동반 입장 불가",
                 imageName: "https://api.cdn.visitjeju.net/photomng/imgpath/201812/21/0e98f747-2431-4e0d-a3d0-e2d0886b3dfc.JPG"),
        Location(name: "돌하르방미술관",
                 locationType: "관광지",
                 address: "제주시 조천읍 북촌서1길 70",
                 coordinates: CLLocationCoordinate2D(latitude: 33.442161, longitude: 126.381630),
                 openHours: "09:00~18:00",
                 dogSize: "소형견, 중형견, 대형견",
                 hashTags: "#미술관 #전시",
                 description: "목줄 2m 이내, 배변 봉투 지참, 관광지 내 카페 동반 입장 가능", imageName:
                    "https://lh3.googleusercontent.com/p/AF1QipMvJkLRS88a9BPt0sssgjDD11zG6lAwutBWWvcf=s1360-w1360-h1020"),
        
        Location(name: "메이즈랜드",
                 locationType: "관광지",
                 address: "제주시 구좌읍 비자림로 2134-47",
                 coordinates: CLLocationCoordinate2D(latitude: 33.392792, longitude: 126.327178),
                 openHours: "09:00~18:00",
                 dogSize: "소형견, 중형견",
                 hashTags: "#미로 #이색관광",
                 description: "반려동물 실내 입장 불가, 반려동물은 케이지 or 유모차 이용 시만 동반입장 가능, 리드줄은 입장 불가",
                 imageName: "https://api.cdn.visitjeju.net/photomng/imgpath/201804/30/27f20040-0ca7-44bc-b1a8-01ad84da2267.jpg"),
        Location(name: "파더스가든",
                 locationType: "관광지",
                 address: "서귀포시 안덕면 병악로 44-33",
                 coordinates: CLLocationCoordinate2D(latitude: 33.382998, longitude: 126.244006),
                 openHours: "09:00~18:00",
                 dogSize: "소형견, 중형견, 대형견",
                 hashTags: "#정원 #대형견",
                 description: "목줄 2m 이내, 배변 봉투 지참, 대형견은 보호자가 컨트롤 가능한 경우 입장 가능",
                 imageName: "https://api.cdn.visitjeju.net/photomng/imgpath/202212/06/952cd053-7f8c-45ef-b054-3f4ce93ff31b.jpg"),
        Location(name: "휴애리자연생활공원",
                 locationType: "관광지",
                 address: "서귀포시 남원읍 신례동로 256",
                 coordinates: CLLocationCoordinate2D(latitude: 33.296708, longitude: 126.252782),
                 openHours: "09:00~19:00",
                 dogSize: "소형견",
                 hashTags: "#공원 #소형견",
                 description: "7kg 미만, 2m 이내, 배변 봉투 지참, 카페내부 입장불가, 관람객이 많은 곳에서는 꼭 안고 다녀야 함",
                 imageName: "https://api.cdn.visitjeju.net/photomng/imgpath/202308/29/d8e383ae-c13c-4432-8f1b-6f3ed3e45ef7.jpg")
        
        
    ]
    
    
}


